### ISSUE TITLE
There should not be a default, should throw and error instead

### ISSUE THREAD

**Issue by jcramer** [Ekliptor/cashp#3]
https://github.com/Ekliptor/cashp/blob/9b63be001d4d50074b11e377e8a0ff743c1b97d1/src/BlockchainApi/BchdProtoGatewayApi.php#L232

**Comment by Ekliptor** [comment]
fixed https://github.com/Ekliptor/cashp/commit/dec731e516ebef42a077d261a2e17db7a6091564
